### ISSUE TITLE
Please take over styling front end UI

### ISSUE THREAD

**Issue by Tadhgin** [naodhu/EazyMart#6]
I've created a crude initial react app for the front end. Can someone please take over styling? I want to continue working on the functionality of the register/login. 
My idea for website functionality begins as:
- Landing page with welcome message, site title display, about/contact us/register/login functional buttons
- 'about' as a pop up blurb 
- 'contact us' as a pop up form 
- 'register' as a pop up form 
- 'login' as usable fields on homepage

Once logged in, continue through car search/browse etc/ I don't know yet

**Comment by Mamad2000** [comment]
Yeah working on the styling right now. I made a merge request for the basics but I’m currently implementing  Element onto the css.
